apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snipe-it
  namespace: "{{ namespaces.snipe_it }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: public
  tls:
  - hosts:
      - "{{ DOMAIN }}"
    secretName: snipe-it-tls
  rules:
  - host: "{{ DOMAIN }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snipe-it
            port:
              number: 80
